easy_admin:
    entities:
#        # List the entity class name you want to manage
        - RaspiPlant\Bundle\BoardBundle\Entity\Board
        - RaspiPlant\Bundle\BoardBundle\Entity\Device
        - RaspiPlant\Bundle\BoardBundle\Entity\Sensor
        - RaspiPlant\Bundle\BoardBundle\Entity\Actuator
