easy_admin:
    site_name: 'FullVibes <em style="font-size: 80%;">RaspiPlant.</em>'
    design:
        brand_color: '#FF5733'
        menu:
            -   label: 'My Account'
                children:
                    #- { label: 'New Board', icon: 'file-new', route: 'createBoard' }
                    - { label: 'Boards', icon: 'chess-board', entity: 'Board', permission: 'ROLE_USER' }
                    - { label: 'Sensors', icon: 'dashboard', entity: 'Sensor', params: { default: 'true' } }
                    - { label: 'Analytics', icon: 'chart-pie', permission: 'ROLE_USER' , route: 'board.dashboard.main'}
            -   label: 'Admin'
                children:
                    - { label: 'Users', icon: 'user', entity: 'User', permission: 'ROLE_ADMIN' }
    entities:
        User:
            class: RaspiPlant\Bundle\AdminBundle\Entity\User
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
#        # List the entity class name you want to manage
        Board:
            class: RaspiPlant\Bundle\BoardBundle\Entity\Board
        Device:
            class: RaspiPlant\Bundle\BoardBundle\Entity\Device
        Sensor:
            class: RaspiPlant\Bundle\BoardBundle\Entity\Sensor
        Actuator:
            class: RaspiPlant\Bundle\BoardBundle\Entity\Actuator
