fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: RaspiPlant\Bundle\BoardBundle\Entity\User
    from_email:
        address: '%env(MAILER_USER)%'
        sender_name: '%env(MAILER_USER)%'
