easy_admin_bundle:
    resource: 'RaspiPlant\Bundle\AdminBundle\Controller\AdminController'
    #resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /admin
    type: annotation
