easyadmin:
  controller: RaspiPlant\Bundle\AdminBundle\Controller\AdminController::indexAction
  path:   /admin/

board.dashboard.main:
  controller: RaspiPlant\Bundle\AdminBundle\Controller\AdminController::indexAction
  path:   /admin/

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
