login:
  controller: RaspiPlant\Bundle\UserBundle\Controller\UserController::loginAction
  path:   /login

homepage:
  controller: RaspiPlant\Bundle\AdminBundle\Controller\AdminController::homepageAction
  path:   /

easyadmin:
  controller: RaspiPlant\Bundle\AdminBundle\Controller\AdminController::indexAction
  path:   /admin/

board.dashboard.main:
  controller: RaspiPlant\Bundle\AdminBundle\Controller\AdminController::indexAction
  path:   /admin/

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
